# Welcome to Plus!
#
# This config file affects your whole blog.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title:                  Base64 Encode And Decode
description:            Convert Images, Texts, Files. Large files support. Encode and Decode Base64 in few clicks with binary preview.
url:                    "https://base64tool.com" # Site base hostname & protocol, e.g. http://example.com
baseurl:                # Site subpath, e.g. /blog
lang:                   en
logo:                   logo-dark.svg
logo_light:             logo-light.svg
permalink:              /:categories/:title/ # Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
date_format:            "%b %-d, %Y" # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
uploads:                /uploads/ # Path to post content assets directory i.e post images, pdfs etc
template:               base

paginate:               6 # Number of posts displayed on blog page
paginate_path:          "/tutorials/:num/" # Blog path

# Default author settings
author:
  name:                 Vladimir Ignatev
  avatar:               avatar-vladimir.png
  title:                Support
  bio:                  I create and maintain handy online tools for people of web.
  url:
  email:                crxextractor@gmail.com
  website:
  facebook:             https://www.facebook.com/ignatev
  flickr:
  dribbble:
  github:               vladignatyev/base64tool
  googleplus:
  instagram:
  linkedin:
  pinterest:
  twitter:              https://twitter.com/v_ignatyev
  vimeo:
  youtube:

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
  vladimir:
    name:                 Vladimir Ignatev
    avatar:               avatar-vladimir.png
    title:                Support
    bio:                  I create and maintain handy online tools for people of web.
    url:
    email:                crxextractor@gmail.com
    website:
    facebook:             https://www.facebook.com/ignatev
    flickr:
    dribbble:
    github:               vladignatyev/base64tool
    googleplus:
    instagram:
    linkedin:
    pinterest:
    twitter:              https://twitter.com/v_ignatyev
    vimeo:
    youtube:

navbar:
  layout:               default # default, center
  color:                dark # text color, dark or light
  animation:            true
  sticky:               true
  search:               false

footer:                 # Default footer image settings
  style:                secondary # default, muted, primary, secondary
  layout:               center # center or columns
  copyright:

mailchimp:
  form_action:          000000
  hidden_name:          000000

google_analytics:       "UA-82390179-7"
google_maps_api_key:    # Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key

disqus:
  shortname:            "base64-tool"

instagram_accesstoken:

donations:
  paypal:
    id:                 # PayPal button ID
    navbar:             # true

# Social share buttons
social_share:
  twitter:              true
  facebook:             true
  linkedin:             true
  pinterest:            true
  reddit:               true

# Social buttons
social_networks:
  email:                ya.na.pochte@gmail.com
  website:
  facebook:             https://www.facebook.com/ignatev
  flickr:
  dribbble:
  github:               https://github.com/vladignatyev/base64tool
  googleplus:
  instagram:
  linkedin:
  pinterest:
  twitter:              https://twitter.com/v_ignatyev
  vimeo:
  youtube:

# Build settings
markdown:               kramdown
highlighter:            rouge
kramdown:
  toc_levels:           "2"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-sitemap
  - jemoji

exclude:
  - vendor
  - .bundle
  - .sass-cache
  - config
  - Gemfile
  - Gemfile.lock
  - node_modules
  - log
  - tmp
  - Rakefile
  - package.json
  - CHANGELOG
  - LICENSE
  - README
  - /docs

sass:
  style:                compressed
  sass_dir: _sass

# collections:
collections:
  blocks:
    output:             false
  sidebars:
    output:             false
  faqs:
    output:             false
  portfolio:
    output:             false

# Defaults
defaults:
  # _posts
  - scope:
      path:                 ""
      type:                 posts
    values:
      layout:               post
      section:              small
      sidebar:
        right:              blog
      comments:             # true
      share:                true
      related:              true
      mailchimp:            true
      navbar:
        transparent:        true
        transparent_color:  light
      header:
        layout:             center
        background_overlay: "rgba(0, 0, 0, 0.5)"
        color:              dark
        header_size:        large
        heading_size:       medium
        parallax:           true
  # _pages
  - scope:
      path:                 ""
      type:                 pages
    values:
      layout:               page
  # _portfolio
  - scope:
      path:                 ""
      type:                 portfolio
    values:
      layout:               page
